included:
  - PodcastHub

excluded:
  - Pods
  - Scripts

analyzer_rules:
  - unused_import

opt_in_rules:
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma
  - conditional_returns_on_newline
  - discouraged_direct_init
  - empty_collection_literal
  - empty_count
  - explicit_init
  - identical_operands
  - implicit_return
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - operator_usage_whitespace
  - pattern_matching_keywords
  - prefer_nimble
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unavailable_function
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher

disabled_rules:
  - line_length

identifier_name:
  min_length: 3
  allowed_symbols: ["_"]
  excluded: ["id", "i", "x", "y"]

type_name:
  min_length: 3

file_length:
  warning: 400
  error: 600

function_body_length:
  warning: 40
  error: 60

type_body_length:
  warning: 200
  error: 300

cyclomatic_complexity:
  warning: 12
  error: 20

nesting:
  type_level: 2

force_cast:
  severity: error

force_try:
  severity: error

unused_import:
  severity: warning

reporter: "xcode"


